% This is the configuration template file for individual analysis 
% _________________________________________________________________________

% Please specify the data type of preprocessed images
% 'nii' for Nifti 4-D format, 'img' for Analyze 7.5 format
% If you would like the script to decide which type to use,
% uncomment the second line and comment the first line
paralist.data_type = 'nii';
% paralist.data_type = [''];

% Please specify the standard preprocessing pipeline you have used
paralist.pipeline = 'swcar';
%paralist.pipeline = 'shortened_swar';

% Please specify the raw data server
paralist.server_path = '/lustre/iCAN/data';
 
% Please specify the individualstats server
paralist.stats_path = '/lustre/iCAN/home/zhuangliping/RR/individualstats';

% Please specify the parent folder of the static data
% For YEAR data structure,      use the first one
% For NONE YEAR data structure, use the second one
paralist.parent_folder   = '';

% Please specify the folder holding statistics results (below 'stats_spm' which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
%paralist.stats_folder = 'temp_stats';
paralist.stats_folder = 'RR/stats_spm8_swcar';

% paralist.parent_folder = 'UCSFBoxer'

% Please specify the .txt file or a cell arry of subjects
% paralist.subjectlist = {'15-11-24.1DST';'15-11-24.2DST';'15-12-10.1DST';'15-12-10.2DST'; ...
%     '15-12-17.1DST';'15-12-17.2DST';'15-12-24.1DST';'15-12-24.2DST';'15-12-31.1DST'};

  load('/lustre/iCAN/home/zhuangliping/RR/RR_scripts/DEP_database.mat');
 for i =[1:50]
  paralist.subjectlist{i,1}=DEP_database{i,2};
 end



% Please specify the .txt file or a cell array of exp_sessions
paralist.exp_sesslist    ={'MS_01';'MS_02';'MS_03';'MS_04';'MS_05';'MS_06';'MS_07';'MS_08'};

% Please specify the task design file (*.m)
% paralist.task_dsgn       = 'taskdesign_emotion_wly.m';
paralist.task_dsgn     = 'taskdesign.m'

% Please specify the file holding contrasts
%paralist.contrastmat = [''];  
paralist.contrastmat     = '/lustre/iCAN/home/zhuangliping/scripts/spm8_scripts/Mainfunctions/contrasts/contrasts_RR.mat';


% Please specify the foler for preprocessed data via standard pipeline
paralist.preprocessed_folder = 'smoothed_spm8';

% Please specify the folder holding statistics results (below 'stats_spm' which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
%paralist.stats_folder = 'temp_stats';
% paralist.stats_folder = 'MS/stats_spm8_swcar';


% Please indicate whether to use head movements (1:Yes; 0:No)
paralist.include_mvmnt = 1;

% Please indicate whether it is based on VolRepair pipeline
% 1: use volrepair pipeline data for individual stats
% 0: use standard pipeline data
% If you set volrepair = 1, set up VolRepair section below
% If you set volrepair = 0, do not set up VolRepair section below 
paralist.include_volrepair = 0;

% -------------------------------------------------------------------------
% VolRepair Preprocessing Setup
% -------------------------------------------------------------------------
% specify the .txt file or a cell array of exp_sessi
% Please specify the volrepair preprocessing pipeline
paralist.volpipeline = 'swavr';

% Please specify the volrepair preprocessed folder
paralist.volrepaired_folder = 'volrepair_spm8';

% Please specify the folder for VolRepaired data (swavrI*)
% the stats folder is under 'stats_spm8' folder (generated by default)
paralist.repaired_stats   = 'stats_spm8_VolRepair';

% -------------------------------------------------------------------------

% Please specify the folder holding batch templates
%paralist.template_path    = '/home/fmri/fmrihome/SPM/spm8_scripts/BatchTemplates';
paralist.template_path    = '/lustre/iCAN/SPM/spm8_scripts/BatchTemplates'; %Shaozheng added

